### ISSUE TITLE
Respect `+optional` comment tag during CRD generation

### ISSUE THREAD

**Issue by twiest** [kubernetes-sigs/controller-tools#137]
According to https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required there are valid use cases for using the `+optional` comment tag without using `omitempty`.

Also note that according to the api-conventions.md doc linked above, `omitempty`'s behavior in Kubernetes "may change in [the] future".

Therefore when generating CRDs, fields should be considered optional if they have either the `+optional` comment tag or `omitempty`.

Currently only `omitempty` is being respected.

A Prototype for this feature can be seen here:
https://github.com/kubernetes-sigs/controller-tools/compare/master...twiest:add_optional_comment_tag_support?expand=1

**Comment by sohankunkerkar** [comment]
@twiest Thanks for bringing this point to our attention. Your changes look good to me! Could you please file a PR for this and add a corresponding test case?

**Comment by twiest** [comment]
@sohankunkerkar ok, sounds good. I'll look into adding that soon.

**Comment by deads2k** [comment]
> According to https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required there are valid use cases for using the `+optional` comment tag without using `omitempty`.

Yeah, there definitely are.  Because CRD validation is tied up with the spec generation, the same forces that drove protobuf to give warnings about required fields apply.  A required field means that old clients may not be able to create new content because they don't know about the new fields being added.  It almost seems like the tag is backwards and we want to give explicit opt-in consideration for required since that represents potentially breaking behavior.

@liggitt I suspect you've given similar advice.

**Comment by twiest** [comment]
@deads2k I created a PR based on your advice.

Since this is changing behavior there are some concerns. Would you mind weighing in on the [PR](https://github.com/kubernetes-sigs/controller-tools/pull/185) I created please?

**Comment by alexkreidler** [comment]
As of now, [v0.2.0-beta.3](https://github.com/kubernetes-sigs/controller-tools/tree/v0.2.0-beta.3) includes PR #211, which adds a `// +kubebuilder:validation:[Required/Optional]` at both the package and field level, which although won't respect the `+optional` tag, should provide a good alternative for most users.

I hope the main `kubebuilder` integrates this ASAP so that we can manage required and optional fields better.

**Comment by damemi** [comment]
@alexkreidler actually, #211 *did* add a simple `+optional` marker as well to support existing use cases: https://github.com/kubernetes-sigs/controller-tools/pull/211/files#diff-98d9e6de300551c3efea14dd61735526R69. With that, I think this issue can be closed as resolved.

Btw, I also have one in progress to add a `+required` marker as well. While our full `+kubebuilder:validation:..` markers are the preferred style going forward, I think it will be good to have both of these for backwards compatibility with what people are used to.

**Comment by damemi** [comment]
I think this can be closed, now that we have the ability to switch the default between optional/required, `// +optional` should be respected when in required mode.
