### ISSUE TITLE
pkg/crd: arrays are not supported as map values

### ISSUE THREAD

**Issue by abursavich** [kubernetes-sigs/controller-tools#213]
```
$ /Users/abursavich/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./api/..." output:crd:artifacts:config=config/crd/bases
/Users/abursavich/go/src/redacted/redacted_types.go:82:24: map values must be a named type, not *ast.ArrayType
```

https://github.com/kubernetes-sigs/controller-tools/blob/455fb28296658dc93252700128c1e28992e7d38e/pkg/crd/schema.go#L288-L296

In my case, I have an object that mirrors a `ConfigMap` with the following field:

```
BinaryData map[string][]byte `json:"binaryData,omitempty"`
```

**Comment by abursavich** [comment]
@DirectXMan12

**Comment by DirectXMan12** [comment]
good catch, we'll want to fix that.

/kind bug

**Comment by damemi** [comment]
@DirectXMan12 based on your comments in https://github.com/kubernetes-sigs/controller-tools/pull/234/ will this only be allowed for byte slices? eg, if I have a `map[string][]string` that needs to have a named type?

**Comment by DirectXMan12** [comment]
talked directly a bit  -- don't want to break existing folks, so we'll add string slice support too.  Don't really want to encourage maps though, as they're generally discouraged for "complex" datatypes (`[]byte` being an exception because its kinda-of a primitive in our APIs): https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps
