### ISSUE TITLE
Support floats?

### ISSUE THREAD

**Issue by skonto** [kubernetes-sigs/controller-tools#245]
In the official docs I still see float support: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/, am I wrong? 
I am currently hitting this error: https://github.com/kubernetes-sigs/controller-tools/blob/abcf7d8d54b0cca0f42c470b705fd3cfe768ede3/pkg/crd/schema.go#L387
Error I get is: `unsupported type "float32"`. I expected my field to be parsed and crd to have a field of type `number` in the yaml format.

**Comment by DirectXMan12** [comment]
so, it's technically supported, but floats are *highly* discouraged (and disallowed in official kubernetes APIs) because they won't round-trip properly, can't actually represent certain numbers exactly, etc (all the normal reasons floats are usually not what you want in a program).  We recommend using `resource.Quantity` or `int32` for your numeric types, in accordance with the Kubernetes API conventions.

Closing this for now, but if you have a compelling argument, I'm happy to reconsider.

**Comment by tothandras** [comment]
I think it would be better to support it and have a warning in the documentation about this. There are scenarios where precision is not important and any workaround might be worse.

**Comment by DirectXMan12** [comment]
it's not just precision -- it's namely that it doesn't round-trip.  I'm can you provide a concrete example here of a scenario where you want to use float?

**Comment by tothandras** [comment]
@DirectXMan12 We have an operator managing [canary releases](https://banzaicloud.com/blog/istio-canary/) (using Istio). The user should be able to provide arbitrary prometheus queries with thresholds (usually a floating number) alongside the built-in metrics (request success rate and request duration).

**Comment by DirectXMan12** [comment]
I think that's probably a better case for quantity than for a normal float, but I see your point.

**Comment by DirectXMan12** [comment]
we could also have an "allowDangerousTypes" option too.

**Comment by tothandras** [comment]
@DirectXMan12 Thank you for considering it! From a UX perspective, by default I would log out a warning with a link to the relevant part of the documentation or a short description, but not fail to build. The `allowDangerousTypes` option could be used to turn off this warning.

**Comment by gaocegege** [comment]
I am glad to share why we need float in CRD spec.

We are implementing an AutoML (a.k.a Hyperparameter tuning) system using kubebuilder. CRD is here https://github.com/kubeflow/katib/tree/master/pkg/apis/controller.

You can see here https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/common/v1alpha3/common_types.go#L42

We allow users to define the goal of the tuning experiment (e.g. When the accuracy reached the goal, we stop the experiment). And the goal is mainly a float number (e.g. 0.99 for accuracy, or 100.5 for loss and so on).

Thus it will be better if we support floats. But it seems that we can have some hack around resource.Quantity

**Comment by DirectXMan12** [comment]
@gaocegege it's not clear to me why that needs *float* in the IEEE sense.  We could improve the syntax for resource.Quantity a bit, but I think resource.Quantity should suffice for your use case.

**Comment by gaocegege** [comment]
Yeah, It also works.

**Comment by loewenstein** [comment]
@DirectXMan12 Would you consider reopening this? We would be willing to contribute float support.

We plan to include another CRD (like a template) in ours and that unfortunately uses a float64.

**Comment by RobbinBaauw** [comment]
`float64` is also used in Kubernetes APIs: 

https://github.com/kubernetes/kubernetes/blob/7580666e0c58b0a34a87fb19beeb682a88e50fac/pkg/kubelet/apis/stats/v1alpha1/types.go#L342-L344

Right now, it is unfortunately impossible to use `stats.PodStats` in your CRD (both because of this error and because `VolumeStats` has an embedded `FsStats` without JSON tags).

**Comment by zlesnr** [comment]
This is surprising.  If I'm meant to use `resource.Quantity`, how does one convert that to a `float64`?

**Comment by matthchr** [comment]
I'm also interested in float support - in our case we're creating CRDs that manage resources whose APIs are beyond our control and these APIs sometimes have float fields. It's possible for us to use strings (and convert before issuing a request to the backing API in our controller), but it would be easier if things were float all the way through, especially because we're already tied to failings of float given we inevitably have to convert to it somehow.

@DirectXMan12 can you explain more what you mean by this?
> it's not just precision -- it's mainly that it doesn't round-trip. Can you provide a concrete example here of a scenario where you want to use float?

As far as I understand it, an IEEE floating point number should round trip just fine? What am I missing?


**In terms of actually solving this, there seem to be a few options:**
1. Allowed, provided a new option `allowDangerousTypes` is specified (suggested by @DirectXMan12  above)
2. Allowed in non-storage versions, disallowed in storage versions
    - This may or may not make sense depending on what exactly the "not round-trippable" comment above means exactly.

Is there a philosophical objection to having this support? Are the maintainers open to a pull request implementing say suggestion 1 above?

**Comment by alexec** [comment]
I've been replacing `float32` with `string `and adding a getter method.

**Comment by matthchr** [comment]
@alvaroaleman - FYI there's already some support for floats which I added in #449 behind a flag.

**Comment by alvaroaleman** [comment]
> @alvaroaleman - FYI there's already some support for floats which I added in #449 behind a flag.

Oh I wasn't aware of that, thanks for mentioning it! Maybe we could improve the handling to instead of falling through into `unsupported type` mention why this is problematic and that it can be overridden through this flag?
