### ISSUE TITLE
Add a version command or option to `controller-gen`

### ISSUE THREAD

**Issue by alexkreidler** [kubernetes-sigs/controller-tools#259]
It would be great to know which version of `controller-gen` we're using in our kubebuilder projects to better diagnose errors and help the community.

Please add a `version` command or `--version` or `-v` flags to controller-gen to help us with this. Thanks a ton!

**Comment by jiachengxu** [comment]
Yes, this would be helpful, since I encountered a similar issue with kubebuilder :https://github.com/kubernetes-sigs/kubebuilder/issues/909. I could try to work on this if help is needed.

**Comment by DirectXMan12** [comment]
/kind feature
/help-wanted

You can more-or-less copy the ldflags/git approach from other projects or bits of kubernetes.  If you've done something similar before, or are willing to do a bit of bash/makefile spelunking, this is a reasonable starter issue.

**Comment by DirectXMan12** [comment]
(we'd probably add this as a `--version` flag)

**Comment by jiachengxu** [comment]
Hi @DirectXMan12, if help is needed, I am willing to work on this issue, any more hints on this?

**Comment by DirectXMan12** [comment]
~~kustomize uses goreleaser, so it's not 1-to-1, but you can get the gist of the general technique here: https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/goreleaser.yaml#L11 / https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/commands/misc/version.go~~

~~Instead of goreleaser, we'd use a script to grab the version info.  The general trick is to run something like `git describe --tags --abbrev=14` and pull the version and commit out of that.
metrics-server uses a giant makefile for doing it, but has extra fancy footwork to stay compatible with what's done in kubernetes/kubernetes: https://github.com/kubernetes-incubator/metrics-server/blob/master/hack/Makefile.buildinfo.  I don't think we need to get that complicated, though.~~

On further thought, since we're generally go-installing, we probably need to make use of https://golang.org/pkg/runtime/debug/#BuildInfo to grab the version info at runtime.  Then we can print that out.
