### ISSUE TITLE
deepcopy-gen should have good support for existing APIs and not fail on difficult fields

### ISSUE THREAD

**Issue by alexkreidler** [kubernetes-sigs/controller-tools#264]
`deepcopy-gen` should be able to run on an existing API codebase with as minimal changes possible and without failing or throwing errors. This means that it should work on structs who also have
- interfaces
- functions
- maps

and other types. It should ignore these fields happily and without issues so we can run `controller-gen object paths=./...` on an existing codebase and it should generate as much as possible, but not fail and only output warnings for fields, etc which are not supported. 

This would help achieve this high-level `kubebuilder` goal: https://github.com/kubernetes-sigs/kubebuilder/issues/863

**Comment by DirectXMan12** [comment]
so most of these are somewhat intentional, in that their presence and the lack of a manual deepcopy method probably indicate a malformed Kubernetes API object.  The issue is mainly that go types serve as the IDL for Kubernetes, but no all Go types and constructs "exist" in the IDL.

Skipping those fields might be fine for deepcopy (albeit pretty surprising), but what do we do for CRD generation?

**Comment by DirectXMan12** [comment]
(to be clear, I'm up for debate here, just laying out the existing thinking)
