### ISSUE TITLE
controller-gen doesn't accept -mod=vendor, downloads source if it can't find the module cache

### ISSUE THREAD

**Issue by ndavidson-pulse** [kubernetes-sigs/controller-tools#327]
I've been trying to vendor a project using kube-builder and controller-gen and build it in our CI system.

However I noticed a pretty significant increase in build-time and when I investigated I discovered that each time I exec controller-gen in a container, if it can't find a populated go package source cache it fetches every dependency from the go.mod / go.sum.

There doesn't appear to be any way to tell controller-gen to use the vendor folder, unless I've missed something?

This seems to hold true for:
`controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/...`
and 
`controller-gen rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases`

Which correspond to the generate and manifests targets in the kube-builder Makefile respectively.

For example, inside a docker container:
```
# du -h /go/pkg/
4.0K    /go/pkg
# controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/...
# du -sh /go/pkg/
196M    /go/pkg/
```

**Comment by alukyan** [comment]
We are running our Go builds in airtight build environment which has vendored dependencies and `controller-gen` fails as it tries to retrieve dependencies from the network which is locked down.

```
[WARN] [19] Error: go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags ignore_autogenerated -- ./...]: exit status 1: go: github.com/Azure/azure-pipeline-go@v0.2.2: Get https://proxy.golang.org/github.com/%21azure/azure-pipeline-go/@v/v0.2.2.mod: dial tcp: lookup proxy.golang.org: no such host
```

`controller-gen` should have an option to run `go list` and other Go commands with `-mod=vendor`

**Comment by alukyan** [comment]
It seems that Go 1.14 now defaults to running `go` tools with `-mod=vendor` if top level directory contains `vendor` subdirectory. We will verify this as we migrate our builds to 1.14 and report results here.

**Comment by ndavidson-pulse** [comment]
Great I hope this works, I never managed to isolate if it was controller-gen calling a tool directly, or the go toolchain. We'll also try with go 1.14 and report back.

**Comment by alukyan** [comment]
/reopen
vendoring has to be supported explicitly.
It should be possible to run builds on secure build agents without downloading all dependencies from Internet

**Comment by drewwells** [comment]
Please reopen, this is still an issue. You have to explicitly set mod=vendor to disable downloading dependencies.

**Comment by ndavidson-pulse** [comment]
/reopen
Definitely still broken for us as well even with go 1.15.x

**Comment by zrhmn** [comment]
I can confirm that this is still an issue. We used [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) to seed our controller as well, and we use vendored builds, too. Running controller-gen inside an environment without internet access fails because it cannot gather information about dependencies.

As deep as we were able to dig in, the `LoadRoots` and `LoadRootsWithConfig` functions in the `pkg/loader` package (specifically [this tools API call here](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/loader/loader.go#L344) are responsible for the failure to obtain information without internet access. We're on controller-gen v0.2.5, but the code in question has not changed much since that tag.

# Possible Fix
We posit that controller-gen _should_ have a way of specifying vendor mode (and any other build options that need to be passed on to go tools by the controller-gen user).

That could be in the form of a separate command-line argument (e.g. `+buildArgs:=[]string`) or as an option on the `+paths` arg (e.g. `+paths="-mod=vendor; ./..."`), and if present, can be passed to the `packages.Load` (and any other tools API calls) as `(*pacakges.Config).BuildFlags` field. But more discussion needs to take place on if/how exactly to handle that.

# Workaround
However, if and until that happens, there is an easy workaround. There is currently an [environment variable `GOFLAGS` ](https://golang.org/cmd/go/#hdr-Environment_variables) that can contain anything extra that needs to be passed to all go tools. The current go/x/tools APIs honor that variable. (Someone else may be able to comment on compatibility with past versions).

We worked around our issue like:

```sh
$ GOFLAGS="-mod=vendor" controller-gen ...
```

but it can also be set in the Makefile, or anything else that would make that environment variable available to controller-gen when it executes.

**Comment by ndavidson-pulse** [comment]
I'm pretty sure I tried GOFLAGS and found by instrumentation that some tools invoked by controller-gen still grabbed packages from upstream - it might have improved in newer versions of golang though.
