### ISSUE TITLE
Marker parsing logic is not compatible with bazel targets

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/controller-tools#376]
If I want to run controller-gen in bazel, I may run something like:
`controller-gen object:headerFile=./hack/boilerplate.go.txt paths="//path/to/my/package:name"`
But our code currently doesn't like `:` when it's not in a "map":
https://github.com/kubernetes-sigs/controller-tools/blob/998668a61585e05bbd875e2fb0d0f536af4cdb58/pkg/markers/parse.go#L353-L380
Currently 3 places use it in the same file: `guessType`, `parseMap` and parsing string. This can be fixed w/o breaking marker syntax.

IMO it should never care what is on the RHS of `=`.

/kind bug

**Comment by mengqiy** [comment]
cc: @DirectXMan12

**Comment by DirectXMan12** [comment]
I think the problem is shell escaping escaping -- you're saying

`paths="//path/to/my/package:name`, but what's getting passed to controller-gen is `paths=//path/to/my/package:name`, which means we're invoking the "guess where the string ends" logic.

If we say `paths='"//path/to/my/package:name"'`, it'll probably work.

**Comment by chrislovecnm** [comment]
@mengqiy did you make any progress on this?
