### ISSUE TITLE
Markers for setting labels and annotations for CRD

### ISSUE THREAD

**Issue by lulf** [kubernetes-sigs/controller-tools#454]
When managing multiple CRDs for a project, it is useful to be able to set labels (and annotations) on them, so that its easy to operate on a group of crds, for instance when deleting them.

The code base is new to me, but I was wondering if it would make sense to generalize the SpecMarker interface to provide a pointer to the ObjectMeta as well, and create a 'metadata' marker that would override the labels and annotations.

**Comment by DirectXMan12** [comment]
We prefer not to have markers for properties that aren't inherently tied to the code.

For example, since changing the "type" of a field (type, validation, defaulting, etc) changes how the code has to deal with that field, it makes sense to generate openapi from the code.  However, the labels & annotations on a particular CRD aren't generally tied to the code that references that resource, so IMO it makes sense to just use normal YAML manipulation mechanisms to do that.

We generally recommend something like a kustomize patch, but the mechanism is up to you.

Does that make sense?

**Comment by DirectXMan12** [comment]
(feel free to continue commenting, but I'm closing this for bookkeeping)

**Comment by lulf** [comment]
@DirectXMan12 I guess it does. The motivation for adding this to controller-gen was to avoid yet another tool to our build chain, and it seemed like a convenient feature for developers. I'll take a look at kustomize and other alternatives, thanks.

**Comment by aanm** [comment]
@DirectXMan12 what about a flag / option to the CRD generator to add these annotations or labels to the generated CRDs? It would complement the existing `controller-gen.kubebuilder.io/version` annotation.

**Comment by muvaf** [comment]
This would be useful for us in Crossplane. For example, I would like to add annotations to AWS resources informing the users which roles they need to give to their IAM user in order for the controller of that CRD to work without issues. We can possibly add an additional tool to patch the generated the CRD but I'd love if we could use a marker because that information is directly related with code (what AWS APIs are called) and keep CRDs manipulated only by controller-tools.
