### ISSUE TITLE
Incorrect crd properties generated for structs defined in k8s/api

### ISSUE THREAD

**Issue by FillZpp** [kubernetes-sigs/controller-tools#457]
Hi folks, 

we define CRD with fields defined in `k8s.io/api`, such as:

```go
import (
    v1 "k8s.io/api/core/v1"
)

type CloneSetSpec struct {
    // ...
    Template v1.PodTemplateSpec `json:"template"`
    // ...
    VolumeClaimTemplates []v1.PersistentVolumeClaim `json:"volumeClaimTemplates,omitempty"`
}
```

For this kind:

- With controller-tools `v0.1.x`, the CRD yaml is generated like [this](https://github.com/openkruise/kruise/blob/master/charts/kruise/v0.5.0/templates/apps_v1alpha1_cloneset.yaml).

    This is ok, all structs defined in `k8s.io/api` are all generated without properties. It is because controller-gen in this version will ignore for `k8s.io/api` https://github.com/kubernetes-sigs/controller-tools/blob/release-0.1/pkg/internal/codegen/parse/crd.go#L457

- But with controller-tools higher than `v0.2.x`, the CRD yaml is generated like [this](https://github.com/openkruise/kruise/blob/master/config/crds/apps.kruise.io_clonesets.yaml).

    It generates properties for structs defined in `k8s.io/api`, which not only makes the CRD yaml much bigger, but also causes incorrect validation.

Problems we have found:
1. For `VolumeClaimTemplates []v1.PersistentVolumeClaim`, it requires user to define `dataSource` in `v1.PersistentVolumeClaim`, which should be optional. ([Issue](https://github.com/openkruise/kruise/issues/301))
2. For `Template v1.PodTemplateSpec`, it will return `The CloneSet "demo" is invalid: type: Required value` when we define `downwardAPI` in `template.spec.volumes`.

So, could we skip to generate properties for structs defined in `k8s.io/api`, just like the `v0.1.x` did?

**Comment by cbandy** [comment]
To me, the validation of core types is a _feature_ rather than a bug. Without it, I would have to implement a validating webhook to verify core types, yes? There are some limitations (declarative defaults, #444) and possibly bugs, but those should be fixed upstream on the core types rather than here.

I see that `PersistentVolumeClaimSpec.DataSource` [has always been tagged `+optional`](https://github.com/kubernetes/kubernetes/commit/e4c82b3d7ba8ec21a1f04656504c999e09eca809), so perhaps that is a bug in this project.
