### ISSUE TITLE
preserveUnknownFields=false doesn't work with crdVersions=v1

### ISSUE THREAD

**Issue by jonnylangefeld** [kubernetes-sigs/controller-tools#476]
`crdVersions=v1` which is the new default, doesn't work in conjunction with `preserveUnknownFields=false`. The `spec.preserveUnknownFields` simply doesn't appear in the crd. There is an [integration test](https://github.com/kubernetes-sigs/controller-tools/pull/365/files#diff-0ab3d8fb1161ec6dd0c0bfde3d82db95R153-R163) for `v1beta1`, but not for `v1`.

I'm running the following command in a kubebuilder repo:
```
controller-gen "crd:preserveUnknownFields=false,crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```

I'm using defaults in my schema and if applying to a `1.16.13-gke.1` cluster, I get:
```
The CustomResourceDefinition "foo.example.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```
If I add spec.preserveUnknownFields manually to the crd it works

My workaround in the makefile right now is
```
yq w -i config/crd/bases/cluster.paas.getcruise.com_clusters.yaml spec.preserveUnknownFields false
```

**Comment by pugangxa** [comment]
I'm hitting the same issue, any ideas?

**Comment by npiganeau** [comment]
I had the same issue here. It was an issue about upgrading from v1beta1 to v1 CRD.
The `spec.preserveUnknownFields` was true in the cluster (probably because that was the default in v1beta1).
When I upgraded to v1, `spec.preserveUnknownFields` was not set in the manifest, but because it was in the cluster, I had the `spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema` error.

The solution was simply to manually add `spec.preserveUnknownFields: false` in the generated CRD manifest and apply it once. 
From then, it worked again when applying `controller-gen` generated manifests (without  `spec.preserveUnknownFields` set).

**Comment by bhiravabhatla** [comment]
Any updates on this?

**Comment by elanv** [comment]
Any updates?

**Comment by kevindelgado** [comment]
I took a stab at this, but it's a bit hairier than I expected. 

Basically, the root cause is that `CRDSpec.PreserveUnknownFields` went from a type *bool in v1beta1 to a type bool in v1. The default value for a bool is false and because the field has an `omitempty` tag on it, a false value will never be written out to the yaml. 

Since the object that gets written to yaml has the correct value of false, there's no easy way to get it to show up. I've hacked together a proof-of-concept of one way to do this that involves aliasing the `apiext.CustomResourceDefinition` type in order to start a conversation, but it's pretty icky and I'm not sure the maintainers will go for it. Check it out at https://github.com/kubernetes-sigs/controller-tools/pull/590

**Comment by derekperkins** [comment]
Still hitting this problem

**Comment by AlexanderYastrebov** [comment]
Now it is trivial to implement like:
```diff
$ git --no-pager diff -- pkg/crd/gen.go
diff --git a/pkg/crd/gen.go b/pkg/crd/gen.go
index 9eb4126b..cb6dd964 100644
--- a/pkg/crd/gen.go
+++ b/pkg/crd/gen.go
@@ -100,6 +100,12 @@ func transformRemoveCRDStatus(obj map[string]interface{}) error {
        return nil
 }
 
+// transformPreserveUnknownFields ensures we spec.preserveUnknownFields=false.
+func transformPreserveUnknownFields(obj map[string]interface{}) error {
+       obj["spec"].(map[interface{}]interface{})["preserveUnknownFields"] = false
+       return nil
+}
+
 func (g Generator) Generate(ctx *genall.GenerationContext) error {
        parser := &Parser{
                Collector: ctx.Collector,
@@ -171,7 +177,7 @@ func (g Generator) Generate(ctx *genall.GenerationContext) error {
                        } else {
                                fileName = fmt.Sprintf("%s_%s.%s.yaml", crdRaw.Spec.Group, crdRaw.Spec.Names.Plural, crdVersions[i])
                        }
-                       if err := ctx.WriteYAML(fileName, headerText, []interface{}{crd}, genall.WithTransform(transformRemoveCRDStatus), genall.WithTransform(genall.TransformRemoveCreationTimestamp)); err != nil {
+                       if err := ctx.WriteYAML(fileName, headerText, []interface{}{crd}, genall.WithTransform(transformRemoveCRDStatus), genall.WithTransform(genall.TransformRemoveCreationTimestamp), genall.WithTransform(transformPreserveUnknownFields)); err != nil {
                                return err
                        }
                }
```
but unfortunately `crd:preserveUnknownFields` marker support was removed by #607

**Comment by sbueringer** [comment]
/remove-lifecycle rotten
/reopen

@AlexanderYastrebov Feel free to open a PR (please with a corresponding test)

**Comment by AlexanderYastrebov** [comment]
@sbueringer @alvaroaleman I guess we can close this as done?

**Comment by sbueringer** [comment]
Yes we can, thx!

/close
