### ISSUE TITLE
controller-gen should allow colon in RBAC role name

### ISSUE THREAD

**Issue by lingsamuel** [kubernetes-sigs/controller-tools#535]
```bash
❯ controller-gen crd:trivialVersions=true rbac:roleName="iris:manager-role" webhook paths=./... output:crd:artifacts:config=config/crd/bases -w
Error: unable to parse option "rbac:roleName=iris:manager-role": [expected comma, got ":" (at <input>:1:14) extra arguments provided: "manager-role" (at <input>:1:15)]
```

**Comment by lingsamuel** [comment]
remove-lifecycle rotten

**Comment by Porges** [comment]
@lingsamuel  Colons are permitted in role names, what you are seeing is a result of the shell interpreting your arguments. Instead of `rbac:roleName="iris:manager-role"`, write `'rbac:roleName="iris:manager-role"'`.

You can see the difference if you compare `echo hello="world"` and `echo 'hello="world"'`; the shell is discarding the double quotes.
